Newline problem
AnuarTB/summer-2019-internships pull request #1
Opened 2018-10-23 14:35 UTC by kvtoraman

My editor added lots of newlines. I hope that won't be a problem for other people.

2018-10-23 14:46 UTC, AnuarTB requested changes
Don't you think it is better to add Korean language requirements in the Notes column?

2018-10-23 14:48 UTC, AnuarTB approved these changes
Yay, first commit! I think it's a small step for a man, but one huge step for the tech community! :1st_place_medal:

2018-10-23 15:00 UTC, kvtoraman commented
I think Korean requirement is a huge change that it needs a table by itself. People may not clearly see "Korean requirement" in notes so they may waste their time, wandering around in the Korean web-page, trying to make it English...

2018-10-23 15:22 UTC, AnuarTB commented on README.md
> +|                                          |          |         |                               |             |
19-21 lines - redundant rows.

2018-10-23 15:25 UTC, AnuarTB commented
I agree with you on this topic, and I wanted to make language requirements more general to have the possibility to extend to other languages as well in the future. How do you think?

2018-10-23 15:26 UTC, AnuarTB commented on README.md
> +### Companies Require Korean
Companies with specific language requirements

2018-10-23 15:26 UTC, AnuarTB commented on README.md
> +| Name                                     | Location | Period  | Notes                         | Korean req. |
Language req.

2018-10-24 05:28 UTC, kvtoraman commented on README.md
> +|                                          |          |         |                               |             |
👍

2018-10-24 05:29 UTC, kvtoraman commented
> I agree with you on this topic, and I wanted to make language requirements more general to have the possibility to extend to other languages as well in the future. How do you think?

Alright, let's see how it goes.

2018-10-24 05:33 UTC, kvtoraman commented
@AnuarTB  updated.

2018-10-24 05:51 UTC, AnuarTB approved these changes

2018-10-24 05:52 UTC, merged